import argparse
import csv
import os
from datetime import datetime

import matplotlib.pyplot as plt


RAW_COLUMNS = {
    "TAG1": ["tag1_raw_a", "tag1_raw_b", "tag1_raw_c"],
    "TAG2": ["tag2_raw_a", "tag2_raw_b", "tag2_raw_c"],
}

FILTERED_COLUMNS = {
    "TAG1": ["tag1_filtered_a", "tag1_filtered_b", "tag1_filtered_c"],
    "TAG2": ["tag2_filtered_a", "tag2_filtered_b", "tag2_filtered_c"],
}

CORRECTED_COLUMNS = {
    "TAG1": ["tag1_corrected_a", "tag1_corrected_b", "tag1_corrected_c"],
    "TAG2": ["tag2_corrected_a", "tag2_corrected_b", "tag2_corrected_c"],
}


def parse_float(value):
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def load_rows(path):
    with open(path, newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def relative_time_seconds(rows):
    times = []
    for idx, row in enumerate(rows):
        raw_time = row.get("time")
        if not raw_time:
            times.append(float(idx))
            continue
        try:
            times.append(datetime.fromisoformat(raw_time))
        except ValueError:
            times.append(float(idx))

    if not times:
        return []

    if isinstance(times[0], datetime):
        start = times[0]
        return [(t - start).total_seconds() if isinstance(t, datetime) else float(i)
                for i, t in enumerate(times)]

    return [float(i) for i in range(len(times))]


def choose_columns(kind):
    if kind == "raw":
        return RAW_COLUMNS
    if kind == "filtered":
        return FILTERED_COLUMNS
    return CORRECTED_COLUMNS


def plot_distances(csv_path, kind, output_path):
    rows = load_rows(csv_path)
    if not rows:
        raise SystemExit(f"No rows found in {csv_path}")

    columns = choose_columns(kind)
    missing = [
        column
        for tag_columns in columns.values()
        for column in tag_columns
        if column not in rows[0]
    ]
    if missing:
        raise SystemExit(
            "This CSV does not contain distance columns. "
            "Run monitor.py again after the logging update, then plot the new log. "
            f"Missing: {', '.join(missing)}"
        )

    x = relative_time_seconds(rows)
    anchor_names = ["A", "B", "C"]

    fig, axes = plt.subplots(2, 1, figsize=(12, 8), sharex=True)
    fig.suptitle(f"UWB {kind} distances")

    for ax, (tag, tag_columns) in zip(axes, columns.items()):
        for anchor_name, column in zip(anchor_names, tag_columns):
            y = [parse_float(row.get(column)) for row in rows]
            ax.plot(x, y, marker="o", markersize=3, linewidth=1.2, label=f"Anchor {anchor_name}")

        ax.set_title(tag)
        ax.set_ylabel("distance (m)")
        ax.grid(True, alpha=0.3)
        ax.legend(loc="best")

    axes[-1].set_xlabel("time (s)")
    fig.tight_layout()
    fig.savefig(output_path, dpi=160)
    print(f"saved {output_path}")


def parse_args():
    parser = argparse.ArgumentParser(description="Plot UWB TAG raw/filtered/corrected distances")
    parser.add_argument("csv_path", help="CSV log generated by monitor.py")
    parser.add_argument("--kind", choices=["raw", "filtered", "corrected"], default="raw")
    parser.add_argument("--output", default=None)
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    output = args.output
    if output is None:
        stem = os.path.splitext(os.path.basename(args.csv_path))[0]
        output = f"{stem}_{args.kind}_distances.png"
    plot_distances(args.csv_path, args.kind, output)
